name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-docker-registry/my-image:${{ github.sha }}

    - name: Deploy Docker container
      uses: phina5656/ssh-action@master
      with:
        host: my-remote-server
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker-compose -f docker-compose.prod.yml up -d
